import "./globals.css";
import { Inter } from "next/font/google";
import Container from "@/components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="bg-fuchsia-600 sticky left-0 top-0">
          <Container>
            <div className="flex justify-between items-center py-6">
              <h1>CRUD NEXT APP</h1>
              <nav>
                <ul className="flex items-center justify-center gap-10">
                  <li>Home</li>
                  <li>About</li>
                  <li>Login</li>
                </ul>
              </nav>
            </div>
          </Container>
        </header>
        <main>
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
