import "./globals.css";
import { Inter } from "next/font/google";
import Container from "@/components/Container";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { IUser } from "../../models/user";
import Provider from "@/components/Provider";
import Headers from "@/components/Header/Headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  interface IUserSession {
    user: IUser;
  }
  const session: IUserSession | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
          <Headers />
          <main>
            <Container>{children}</Container>
          </main>
        </Provider>
      </body>
    </html>
  );
}
